import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Cheeseburger Deluxe',
    description: 'A juicy beef patty with melted cheddar, lettuce, tomato, and our special sauce on a toasted bun.',
    price: 8.99,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.5,
    bestseller: true,
  },
  {
    id: 2,
    name: 'Classic Pepperoni',
    description: 'A crowd-pleaser with rich tomato sauce, mozzarella, and a generous layer of pepperoni.',
    price: 12.99,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.8,
    bestseller: true,
  },
  {
    id: 3,
    name: 'Crispy Golden Fries',
    description: 'Perfectly golden and crispy french fries, lightly salted and served hot.',
    price: 3.49,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.2,
  },
  {
    id: 4,
    name: 'Ice-Cold Cola',
    description: 'A refreshing can of classic cola to quench your thirst and complete your meal.',
    price: 1.99,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.6,
  },
  {
    id: 5,
    name: 'Veggie Supreme Pizza',
    description: 'Loaded with fresh bell peppers, onions, olives, and mushrooms on our classic tomato base.',
    price: 14.99,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.4,
  },
  {
    id: 6,
    name: 'Spicy Chicken Burger',
    description: 'A fiery, crispy chicken fillet with spicy mayo, jalapeños, and fresh lettuce.',
    price: 9.99,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.7,
    bestseller: true,
  },
  {
    id: 7,
    name: 'Crunchy Onion Rings',
    description: 'Thick-cut onion rings battered and fried to a perfect golden brown. Served with dipping sauce.',
    price: 4.99,
    category: 'Fries',
    image: 'https://placehold.co/600x400.png',
    rating: 4.3,
  },
  {
    id: 8,
    name: 'Fresh Lemonade',
    description: 'A zesty and refreshing homemade lemonade, perfect for a sunny day.',
    price: 2.49,
    category: 'Beverages',
    image: 'https://placehold.co/600x400.png',
    rating: 4.5,
  },
  {
    id: 9,
    name: 'Family Feast Combo',
    description: 'The perfect meal for four: 2 large pizzas, a family-size fries, and a 2-liter soda.',
    price: 29.99,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.9,
  },
  {
    id: 10,
    name: 'Margherita Pizza',
    description: 'Simple yet delicious, with fresh basil, mozzarella, and our signature tomato sauce.',
    price: 10.99,
    category: 'Pizza',
    image: 'https://placehold.co/600x400.png',
    rating: 4.1,
  },
  {
    id: 11,
    name: 'Bacon BBQ Burger',
    description: 'Smoky BBQ sauce, crispy bacon, and melted cheddar top our classic beef patty.',
    price: 10.49,
    category: 'Burgers',
    image: 'https://placehold.co/600x400.png',
    rating: 4.6,
  },
  {
    id: 12,
    name: 'Burger & Fries Combo',
    description: 'A classic Cheeseburger Deluxe paired with a medium portion of our crispy golden fries.',
    price: 11.49,
    category: 'Combos',
    image: 'https://placehold.co/600x400.png',
    rating: 4.7,
  },
];
